version: "2.0"

services:
  postgres:
    image: postgres:9.6.8-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8neEmdvl
    volumes:
      - ./docker-persistent/postgres/data:/var/lib/postgresql/data
      - ./docker-persistent/conf/postgresql.conf:/etc/postgresql.conf:ro
    command: postgres -c config_file=/etc/postgresql.conf

  sync:
    build:
      context: .
      dockerfile: docker/Dockerfile.sync
    restart: always
    volumes:
      - ./docker-persistent/app/git:/app/git
      - ./docker-persistent/app/log:/app/log
      - ./docker-persistent/conf/app.conf:/app/conf/app.conf:ro
    depends_on:
      - postgres

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    restart: always
    ports:
    - 8000:8000
    volumes:
      - ./docker-persistent/app/git:/app/git
      - ./docker-persistent/app/log:/app/log
      - ./docker-persistent/conf/app.conf:/app/conf/app.conf:ro
    depends_on:
      - sync
