version: "2.0"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 8neEmdvl
    volumes:
      - ./docker-persistent/mongo/data:/data/db

  sync:
    build:
      context: .
      dockerfile: docker/Dockerfile.sync
    restart: always
    volumes:
      - ./docker-persistent/app/git:/app/git
      - ./docker-persistent/app/log:/app/log
      - ./docker-persistent/conf/app.conf:/app/conf/app.conf:ro
    depends_on:
      - mongo

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    restart: always
    ports:
    - 8000:8000
    volumes:
      - ./docker-persistent/app/git:/app/git
      - ./docker-persistent/app/log:/app/log
      - ./docker-persistent/conf/app.conf:/app/conf/app.conf:ro
    depends_on:
      - sync
